version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
      - XIMILAR_API_TOKEN=fb511412f7ba055c38d74e4664d06886b7bd375c
